previews:
  generation: automatic # Enable preview environments
services:
  # A static site
  - type: web
    name: ribsburger
    runtime: static
    staticPublishPath: ./
    previews:
      generation: automatic # Enable service previews
    buildFilter:
      paths:
        - ./**/*.js
      ignoredPaths:
        - ./**/*.test.js
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
    routes:
      - type: redirect
        source: /old
        destination: /new
      - type: rewrite
        source: /a/*
        destination: /a
